
import { ThemeConfig } from './types.js';

export const THEMES: ThemeConfig[] = [
  {
    id: 'home',
    name: 'WELCOME TO M-CLEOD',
    subtitle: 'THE CHRONICLE OF TIME',
    monthName: 'The Nexus',
    monthIndex: 0,
    bgGradient: 'from-slate-900 via-blue-900 to-black',
    accentColor: 'text-cyan-400',
    fontFamily: 'Orbitron',
    icon: '✨',
    description: 'The core of the multi-verse. Where all months converge.',
    particleType: 'stars',
    geminiPrompt: 'Give me a welcoming, mysterious message about a grand journey through 12 thematic worlds of a calendar.',
    gameTitle: 'Nexus Void-Runner'
  },
  {
    id: 'january',
    name: 'FROST KINGDOM',
    subtitle: 'THE FIRST CHILL',
    monthName: 'January',
    monthIndex: 0,
    bgGradient: 'from-blue-500 via-cyan-700 to-blue-900',
    accentColor: 'text-blue-300',
    fontFamily: 'Inter',
    icon: '❄️',
    description: 'A land of eternal ice and shimmering crystals.',
    particleType: 'snow',
    geminiPrompt: 'Provide a short, poetic quote about the quiet beauty of a frozen winter morning.',
    gameTitle: 'Cryo-Climb'
  },
  {
    id: 'february',
    name: 'WIZARDS & MAGIC',
    subtitle: 'THE ARCANE SANCTUM',
    monthName: 'February',
    monthIndex: 1,
    bgGradient: 'from-indigo-900 via-purple-900 to-black',
    accentColor: 'text-purple-400',
    fontFamily: 'Cinzel Decorative',
    icon: '🧙‍♂️',
    description: 'Where ley lines cross and ancient spells are woven.',
    particleType: 'stars',
    geminiPrompt: 'Share a cryptic wizard wisdom for the month of February.',
    gameTitle: 'Spellbinder Duel'
  },
  {
    id: 'march',
    name: 'PIRATES & SEA',
    subtitle: 'TIDES OF FORTUNE',
    monthName: 'March',
    monthIndex: 2,
    bgGradient: 'from-emerald-900 via-teal-800 to-blue-900',
    accentColor: 'text-yellow-500',
    fontFamily: 'Pirata One',
    icon: '🏴‍☠️',
    description: 'Navigate the treacherous waters of the Obsidian Coast.',
    particleType: 'bubbles',
    geminiPrompt: 'Give me a short pirate-themed greeting for a sailor entering March.',
    gameTitle: 'Scurvy Scramble'
  },
  {
    id: 'april',
    name: 'ENCHANTED FOREST',
    subtitle: 'WHISPERS IN THE LEAVES',
    monthName: 'April',
    monthIndex: 3,
    bgGradient: 'from-green-900 via-emerald-800 to-green-950',
    accentColor: 'text-lime-400',
    fontFamily: 'MedievalSharp',
    icon: '🌿',
    description: 'Awaken the spirits of the spring within the deep woods.',
    particleType: 'leaves',
    geminiPrompt: 'What would a forest spirit say about the arrival of spring in April?',
    gameTitle: 'Spirit Trail'
  },
  {
    id: 'may',
    name: 'CYBERPUNK NEON',
    subtitle: 'NIGHT CITY VIBES',
    monthName: 'May',
    monthIndex: 4,
    bgGradient: 'from-fuchsia-950 via-black to-blue-950',
    accentColor: 'text-pink-500',
    fontFamily: 'Orbitron',
    icon: '🤖',
    description: 'High tech, low life. The future is now.',
    particleType: 'rain',
    geminiPrompt: 'Write a short cyberpunk-style haiku for the month of May.',
    gameTitle: 'Neon Hack'
  },
  {
    id: 'june',
    name: 'EGYPTIAN SANDS',
    subtitle: 'LEGACY OF RA',
    monthName: 'June',
    monthIndex: 5,
    bgGradient: 'from-orange-400 via-yellow-600 to-amber-900',
    accentColor: 'text-yellow-200',
    fontFamily: 'Cinzel Decorative',
    icon: '🌞',
    description: 'Ancient pyramids under the relentless desert sun.',
    particleType: 'none',
    geminiPrompt: 'A short blessing from an Egyptian sun deity for June.',
    gameTitle: 'Anubis Ascent'
  },
  {
    id: 'july',
    name: 'SYNTHWAVE SUNSET',
    subtitle: 'RETRO 80S RADICAL',
    monthName: 'July',
    monthIndex: 6,
    bgGradient: 'from-purple-600 via-pink-500 to-orange-400',
    accentColor: 'text-cyan-300',
    fontFamily: 'Orbitron',
    icon: '🕶️',
    description: 'Driving into the grid as the digital sun never sets.',
    particleType: 'stars',
    geminiPrompt: 'Give me a radical 80s movie tagline for July.',
    gameTitle: 'Retro Racer'
  },
  {
    id: 'august',
    name: 'GALACTIC FRONTIER',
    subtitle: 'ACROSS THE STARS',
    monthName: 'August',
    monthIndex: 7,
    bgGradient: 'from-black via-slate-900 to-indigo-950',
    accentColor: 'text-blue-300',
    fontFamily: 'Orbitron',
    icon: '🚀',
    description: 'Exploring the outer rim of the Andromeda galaxy.',
    particleType: 'stars',
    geminiPrompt: 'A short communication log from a deep space explorer in August.',
    gameTitle: 'Orbit Defense'
  },
  {
    id: 'september',
    name: 'STEAMPUNK COG',
    subtitle: 'CLOCKED IN TIME',
    monthName: 'September',
    monthIndex: 8,
    bgGradient: 'from-amber-950 via-stone-800 to-orange-950',
    accentColor: 'text-orange-400',
    fontFamily: 'Special Elite',
    icon: '⚙️',
    description: 'Steam-driven machinery and brass-clad adventures.',
    particleType: 'none',
    geminiPrompt: 'A short instruction from a steampunk inventor for the start of September.',
    gameTitle: 'Crank-Shaft'
  },
  {
    id: 'october',
    name: 'SPOOKY HOLLOW',
    subtitle: 'NIGHT OF THE HARVEST',
    monthName: 'October',
    monthIndex: 9,
    bgGradient: 'from-black via-purple-950 to-orange-900',
    accentColor: 'text-orange-600',
    fontFamily: 'MedievalSharp',
    icon: '🎃',
    description: 'Where the veil is thin and the shadows come alive.',
    particleType: 'leaves',
    geminiPrompt: 'A spooky 2-sentence story for a dark October night.',
    gameTitle: 'Grave Digger'
  },
  {
    id: 'november',
    name: 'ZEN GARDEN',
    subtitle: 'THE HARMONY OF FALL',
    monthName: 'November',
    monthIndex: 10,
    bgGradient: 'from-stone-800 via-red-950 to-stone-900',
    accentColor: 'text-red-400',
    fontFamily: 'Inter',
    icon: '🏮',
    description: 'Peaceful reflection as the last leaves descend.',
    particleType: 'leaves',
    geminiPrompt: 'A short Zen koan about change and transition for November.',
    gameTitle: 'Petal Fall'
  },
  {
    id: 'december',
    name: 'COZY CHRONICLE',
    subtitle: 'THE GRAND FINALE',
    monthName: 'December',
    monthIndex: 11,
    bgGradient: 'from-red-900 via-green-950 to-black',
    accentColor: 'text-red-500',
    fontFamily: 'Cinzel Decorative',
    icon: '🎄',
    description: 'Gather round the hearth for the year\'s end.',
    particleType: 'snow',
    geminiPrompt: 'A warm, festive greeting for the final month of the M-CLEOD.',
    gameTitle: 'Gift Grab'
  }
];
